# Generated by Django 5.1.4 on 2024-12-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='event',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='event',
            name='images',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='Default Address', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_customized',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='max_people_numbers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='timelines',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('PUBLIC', 'public'), ('PERSONAL', 'personal'), ('PRIVATE', 'private')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='followers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='region',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
