# Generated by Django 5.1.4 on 2024-12-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_additional_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('PUBLIC', 'Public'), ('PERSONAL', 'Personal'), ('PRIVATE', 'Private')], max_length=10, null=True),
        ),
    ]
