# Generated by Django 5.1.4 on 2024-12-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
